### ISSUE TITLE
Spotify 1.0.94 has libcurl as last entry

### ISSUE THREAD

**Issue by mleise** [saboya/spotify-patcher#1]
Your prediction eventually came true. Spotify 1.0.94.262.g3d5c231c can't be patched with the script right now. I've hacked the script up for now and it works for me. I just wanted to let you know in case you haven't noticed yet.

**Comment by saboya** [comment]
I had noticed it yesterday, but didn't get around to fix it yet. I just updated the script and should be working now.

Thanks for the heads up!
