### ISSUE TITLE
Patcher not working with systems using languages other than English

### ISSUE THREAD

**Issue by mig99d** [saboya/spotify-patcher#2]
My machine is using Portuguese (LANG="pt_PT.utf8@euro") as the default language locale. The output of readelf is also fully translated. In my case the patcher is not able to find the "File:" string when parsing the readelf output and so fails to do anything.
I managed to work around it by changing the LANG environment variable to "en" when running the script. 

I think a reasonable and easy way to fix this is to have the script itself override the LANG variable, so that the output of readelf can be correctly parsed even if the system default is not English. Most machines should have English support, and if not then the script as is won't work anyway.

**Comment by saboya** [comment]
Should be fixed with https://github.com/saboya/spotify-patcher/commit/3f1577e3a0407bbe569c4353f7360a18df61d0ed.

Thanks for the report!
